package eventapp;

import java.awt.Font;
import java.io.File;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * @author Christopher Forget
 */

public class MainFrame extends javax.swing.JFrame {

    ArrayList<Observer> observers = new ArrayList<>();
    private boolean isAdding;

    public MainFrame(Controller controller) {
        initComponents();
        this.addObserver(controller);
        this.isAdding = false;
        tableEvents.getTableHeader().setFont(new Font("Arial", Font.PLAIN, 18));
        jPanelAdd.setVisible(false);
        buttonAdd.setEnabled(false);
        buttonModify.setEnabled(false);
        buttonDelete.setEnabled(false);
    }
    
    public void addObserver(Observer o){
        observers.add(o);
    }
    public void removeObserver(Observer o){
        observers.remove(o);
    }
            
    public void notifyNewEvent(Event event){
        for(Observer observer: observers){
            observer.addEvent(event);
        }
    }
    
    public void notifyModifyEvent(int row, Event event){
        for(Observer observer: observers){
            observer.modifyEvent(row, event);
        }
    }
        
    public void notifyLoadTable(DefaultTableModel model){
        for(Observer observer: observers){
            observer.loadTreeToInterface(model);
        }
    }
        
    public Event notifyGetEvent(int row){
        for(Observer observer: observers){
            Event event = observer.getEvent(row);
            return event;
        }
        return null;
    }
    
    public void notifyRemoveEvent(int row){
        for(Observer observer: observers){
            observer.removeEvent(row);
        }
    }
    
    public void notifyOpenRSS(String url) throws Exception{
        for(Observer observer: observers){
            observer.openRSS(url);
        }
    }
    
    public void notifySaveToXMLFile(String url) throws Exception{
        for(Observer observer: observers){
            observer.saveToXMLFile(url);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        JMenuItemColler = new javax.swing.JMenuItem();
        javax.swing.JLayeredPane jLayeredPane1 = new javax.swing.JLayeredPane();
        javax.swing.JPanel jPanelDefault = new javax.swing.JPanel();
        javax.swing.JScrollPane jScrollPane1 = new javax.swing.JScrollPane();
        tableEvents = new javax.swing.JTable();
        buttonAdd = new javax.swing.JButton();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        buttonModify = new javax.swing.JButton();
        buttonDelete = new javax.swing.JButton();
        jPanelAdd = new javax.swing.JPanel();
        jLabelAddTitle = new javax.swing.JLabel();
        javax.swing.JLabel jLabel8 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel3 = new javax.swing.JLabel();
        jTextFieldTitle = new javax.swing.JTextField();
        jFormattedTextFieldDate = new javax.swing.JFormattedTextField();
        javax.swing.JLabel jLabel6 = new javax.swing.JLabel();
        jTextFieldLink = new javax.swing.JTextField();
        javax.swing.JLabel jLabel4 = new javax.swing.JLabel();
        jTextFieldGuid = new javax.swing.JTextField();
        javax.swing.JButton jButtonAddAccept = new javax.swing.JButton();
        javax.swing.JButton jButtonAddCancel = new javax.swing.JButton();
        javax.swing.JLabel jLabel5 = new javax.swing.JLabel();
        jTextFieldDescription = new javax.swing.JTextField();
        jCheckBoxGuid = new javax.swing.JCheckBox();
        jCheckBoxDescription = new javax.swing.JCheckBox();
        javax.swing.JMenuBar jMenuBar1 = new javax.swing.JMenuBar();
        javax.swing.JMenu jMenuFile = new javax.swing.JMenu();
        javax.swing.JMenuItem jMenuItemOpen = new javax.swing.JMenuItem();
        javax.swing.JMenuItem jMenuItemSaveAs = new javax.swing.JMenuItem();
        javax.swing.JPopupMenu.Separator jSeparator1 = new javax.swing.JPopupMenu.Separator();
        javax.swing.JMenuItem jMenuItemClose = new javax.swing.JMenuItem();
        javax.swing.JMenu jMenuEdit = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        JMenuItemColler.setLabel("Coller");
        JMenuItemColler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuItemCollerActionPerformed(evt);
            }
        });
        jPopupMenu1.add(JMenuItemColler);
        JMenuItemColler.getAccessibleContext().setAccessibleName("Coller");

        jPopupMenu1.getAccessibleContext().setAccessibleParent(jTextFieldTitle);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EventApp");
        setMinimumSize(new java.awt.Dimension(600, 490));

        jLayeredPane1.setMinimumSize(new java.awt.Dimension(20, 20));
        jLayeredPane1.setPreferredSize(new java.awt.Dimension(1200, 870));
        jLayeredPane1.setLayout(new javax.swing.OverlayLayout(jLayeredPane1));

        jPanelDefault.setPreferredSize(new java.awt.Dimension(1200, 870));

        jScrollPane1.setColumnHeaderView(null);
        jScrollPane1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jScrollPane1.setPreferredSize(new java.awt.Dimension(1160, 670));

        tableEvents.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tableEvents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title", "Link", "Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableEvents.setMaximumSize(new java.awt.Dimension(2147483647, 7000));
        tableEvents.setMinimumSize(new java.awt.Dimension(20, 20));
        tableEvents.setPreferredSize(new java.awt.Dimension(1160, 670));
        tableEvents.setRowHeight(40);
        jScrollPane1.setViewportView(tableEvents);
        if (tableEvents.getColumnModel().getColumnCount() > 0) {
            tableEvents.getColumnModel().getColumn(0).setMinWidth(400);
            tableEvents.getColumnModel().getColumn(0).setPreferredWidth(400);
            tableEvents.getColumnModel().getColumn(1).setResizable(false);
            tableEvents.getColumnModel().getColumn(1).setPreferredWidth(400);
        }

        buttonAdd.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        buttonAdd.setText("Nouveau");
        buttonAdd.setFocusable(false);
        buttonAdd.setMaximumSize(new java.awt.Dimension(100, 30));
        buttonAdd.setMinimumSize(new java.awt.Dimension(100, 30));
        buttonAdd.setPreferredSize(new java.awt.Dimension(150, 60));
        buttonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eventapp/logoTeluq.png"))); // NOI18N
        jLabel1.setText("Fils de nouvelles RSS de l'université");

        buttonModify.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        buttonModify.setText("Modifier");
        buttonModify.setFocusable(false);
        buttonModify.setMaximumSize(new java.awt.Dimension(170, 70));
        buttonModify.setMinimumSize(new java.awt.Dimension(170, 70));
        buttonModify.setPreferredSize(new java.awt.Dimension(150, 60));
        buttonModify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonModifyActionPerformed(evt);
            }
        });

        buttonDelete.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        buttonDelete.setText("Supprimer");
        buttonDelete.setFocusable(false);
        buttonDelete.setMaximumSize(new java.awt.Dimension(170, 70));
        buttonDelete.setMinimumSize(new java.awt.Dimension(170, 70));
        buttonDelete.setPreferredSize(new java.awt.Dimension(150, 60));
        buttonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelDefaultLayout = new javax.swing.GroupLayout(jPanelDefault);
        jPanelDefault.setLayout(jPanelDefaultLayout);
        jPanelDefaultLayout.setHorizontalGroup(
            jPanelDefaultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDefaultLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelDefaultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelDefaultLayout.createSequentialGroup()
                        .addComponent(buttonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonModify, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
        jPanelDefaultLayout.setVerticalGroup(
            jPanelDefaultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDefaultLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 672, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanelDefaultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonModify, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        jLayeredPane1.add(jPanelDefault);

        jPanelAdd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelAdd.setPreferredSize(new java.awt.Dimension(700, 543));

        jLabelAddTitle.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabelAddTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAddTitle.setText("Ajouter un événement");
        jLabelAddTitle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabelAddTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelAddTitle.setMaximumSize(new java.awt.Dimension(174, 46));
        jLabelAddTitle.setMinimumSize(new java.awt.Dimension(174, 46));
        jLabelAddTitle.setPreferredSize(new java.awt.Dimension(174, 46));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setText("Titre");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Date");

        jTextFieldTitle.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextFieldTitle.setComponentPopupMenu(jPopupMenu1);
        jTextFieldTitle.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextFieldTitle.setPreferredSize(new java.awt.Dimension(659, 30));
        jTextFieldTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTitleActionPerformed(evt);
            }
        });

        jFormattedTextFieldDate.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jFormattedTextFieldDate.setPreferredSize(new java.awt.Dimension(659, 30));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("Lien");

        jTextFieldLink.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextFieldLink.setPreferredSize(new java.awt.Dimension(659, 30));
        jTextFieldLink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLinkActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Guid");

        jTextFieldGuid.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextFieldGuid.setPreferredSize(new java.awt.Dimension(659, 30));

        jButtonAddAccept.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButtonAddAccept.setText("Terminer");
        jButtonAddAccept.setFocusable(false);
        jButtonAddAccept.setPreferredSize(new java.awt.Dimension(150, 60));
        jButtonAddAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddAcceptActionPerformed(evt);
            }
        });

        jButtonAddCancel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButtonAddCancel.setText("Annuler");
        jButtonAddCancel.setPreferredSize(new java.awt.Dimension(150, 60));
        jButtonAddCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddCancelActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("Description");

        jTextFieldDescription.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextFieldDescription.setPreferredSize(new java.awt.Dimension(659, 30));

        jCheckBoxGuid.setText("(Même que lien)");
        jCheckBoxGuid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxGuidActionPerformed(evt);
            }
        });

        jCheckBoxDescription.setText("(Même que titre)");
        jCheckBoxDescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxDescriptionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAddLayout = new javax.swing.GroupLayout(jPanelAdd);
        jPanelAdd.setLayout(jPanelAddLayout);
        jPanelAddLayout.setHorizontalGroup(
            jPanelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAddLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelAddLayout.createSequentialGroup()
                        .addComponent(jButtonAddAccept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonAddCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextFieldDescription, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldGuid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldLink, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addGroup(jPanelAddLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBoxGuid))
                    .addGroup(jPanelAddLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBoxDescription))
                    .addComponent(jLabelAddTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        jPanelAddLayout.setVerticalGroup(
            jPanelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAddLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabelAddTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldLink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jCheckBoxGuid))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldGuid, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jFormattedTextFieldDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jCheckBoxDescription))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonAddAccept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAddCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        jLayeredPane1.setLayer(jPanelAdd, javax.swing.JLayeredPane.MODAL_LAYER);
        jLayeredPane1.add(jPanelAdd);

        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMenuBar1.setFocusable(false);
        jMenuBar1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jMenuBar1.setPreferredSize(new java.awt.Dimension(99, 30));

        jMenuFile.setText("Fichier");
        jMenuFile.setFocusable(false);
        jMenuFile.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jMenuItemOpen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemOpen.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jMenuItemOpen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eventapp/open-folder.png"))); // NOI18N
        jMenuItemOpen.setText("Ouvrir");
        jMenuItemOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemOpenActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemOpen);

        jMenuItemSaveAs.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemSaveAs.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jMenuItemSaveAs.setText("Sauvegarder sous");
        jMenuItemSaveAs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSaveAsActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemSaveAs);
        jMenuFile.add(jSeparator1);

        jMenuItemClose.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemClose.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jMenuItemClose.setText("Fermer");
        jMenuItemClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCloseActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemClose);

        jMenuBar1.add(jMenuFile);

        jMenuEdit.setText("Edit");
        jMenuEdit.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eventapp/plus.png"))); // NOI18N
        jMenuItem3.setText("Nouveau");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenuEdit.add(jMenuItem3);
        jMenuEdit.add(jSeparator2);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_DELETE, 0));
        jMenuItem1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eventapp/bin.png"))); // NOI18N
        jMenuItem1.setText("Supprimer");
        jMenuEdit.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eventapp/refresh.png"))); // NOI18N
        jMenuItem2.setText("Modifier");
        jMenuEdit.add(jMenuItem2);

        jMenuBar1.add(jMenuEdit);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1216, 908));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddActionPerformed
        // TODO add your handling code here:
        isAdding = true;
        buttonAdd.setEnabled(false);
        buttonModify.setEnabled(false);
        buttonDelete.setEnabled(false);
        tableEvents.setEnabled(false);
        jLabelAddTitle.setText("Ajouter un événement");
        jPanelAdd.setVisible(true);
    }//GEN-LAST:event_buttonAddActionPerformed

    private void buttonModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonModifyActionPerformed
        // TODO add your handling code here:
        int selectedRow = tableEvents.getSelectedRow();
        
        if (selectedRow < 0){
            JOptionPane.showMessageDialog(this, "Aucune sélection, veuillez sélectionner une rangée.", "Erreur de sélection", JOptionPane.ERROR_MESSAGE);
        } else {
            buttonAdd.setEnabled(false);
            buttonModify.setEnabled(false);
            buttonDelete.setEnabled(false);
            tableEvents.setEnabled(false);
            jLabelAddTitle.setText("Modifier un événement");
            jPanelAdd.setVisible(true);  
                     
            int row = tableEvents.getSelectedRow();
            Event event = this.notifyGetEvent(row);
            
            String title = event.getTitle();
            String link = event.getLink();
            String guid = event.getGuid();
            String pubDate = event.getPubDate();
            String desc = event.getDescription();
            
            jTextFieldTitle.setText(title);
            jTextFieldLink.setText(link);
            jTextFieldGuid.setText(guid);
            jFormattedTextFieldDate.setText(pubDate);
            jTextFieldDescription.setText(desc);                     
        }
    }//GEN-LAST:event_buttonModifyActionPerformed

    private void buttonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteActionPerformed
        // TODO add your handling code here:
        int selectedRow = tableEvents.getSelectedRow();
        
        if (selectedRow < 0){
            JOptionPane.showMessageDialog(this, "Aucune sélection, veuillez sélectionner une rangée.", "Erreur de sélection", JOptionPane.ERROR_MESSAGE);
        } else {
            int row = tableEvents.getSelectedRow();       
            int del = JOptionPane.showConfirmDialog(this,"Etes-vous sur de vouloir supprimer cette rangée?");
            if(del == 0){
                this.notifyRemoveEvent(row);
            }
            
            // Reload tableEvents
            DefaultTableModel model = (DefaultTableModel) tableEvents.getModel();
            this.notifyLoadTable(model);
        }
    }//GEN-LAST:event_buttonDeleteActionPerformed

    private void jTextFieldLinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLinkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLinkActionPerformed

    private void jTextFieldTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTitleActionPerformed

    private void jButtonAddAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddAcceptActionPerformed
        // TODO add your handling code here:
                
        // Get text fields entries
        String strTitle = jTextFieldTitle.getText();
        String strPubDate = jFormattedTextFieldDate.getText();
        String strLink = jTextFieldLink.getText();
        String strGuid;
        if(jCheckBoxGuid.isSelected()){
            strGuid = jTextFieldLink.getText();
        } else {
            strGuid = jTextFieldGuid.getText();
        }
        String strDescription;
        if(jCheckBoxDescription.isSelected()){
            strDescription = jTextFieldTitle.getText();
        } else {
            strDescription = jTextFieldDescription.getText();
        }
        
        if (strTitle.isEmpty() || strPubDate.isEmpty() || strLink.isEmpty() || strGuid.isEmpty() || strDescription.isEmpty()){
            JOptionPane.showMessageDialog(this, "Formulaire incomplet, veuillez remplir toutes les cases", "Erreur de saisie", JOptionPane.ERROR_MESSAGE);
        } else {
            // Create an event and send to controller.
            Event newEvent = new Event(strTitle, strLink, strGuid, strPubDate, strDescription);
            if (isAdding) { 
                this.notifyNewEvent(newEvent);
                isAdding = false;
            } else {
                this.notifyModifyEvent(tableEvents.getSelectedRow(),newEvent);
            }
        
            // Refresh tableEvents
            DefaultTableModel model = (DefaultTableModel) tableEvents.getModel();
            this.notifyLoadTable(model);
        
            // Reset and close form
            jTextFieldTitle.setText("");
            jFormattedTextFieldDate.setText("");
            jTextFieldLink.setText("");
            jTextFieldGuid.setText("");
            jTextFieldDescription.setText("");
            jTextFieldGuid.setEnabled(true);
            jTextFieldDescription.setEnabled(true);
            jCheckBoxGuid.setSelected(false);
            jCheckBoxDescription.setSelected(false);
            jPanelAdd.setVisible(false);     
            
            buttonAdd.setEnabled(true);
            buttonModify.setEnabled(true);
            buttonDelete.setEnabled(true);
            tableEvents.setEnabled(true);
        }
    }//GEN-LAST:event_jButtonAddAcceptActionPerformed

    private void jButtonAddCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddCancelActionPerformed
        // TODO add your handling code here:
        // Reset and close form
        isAdding = false;
        jTextFieldTitle.setText("");
        jFormattedTextFieldDate.setText("");
        jTextFieldLink.setText("");
        jTextFieldGuid.setText("");
        jTextFieldDescription.setText("");
        jTextFieldGuid.setEnabled(true);
        jCheckBoxGuid.setSelected(false);
        jPanelAdd.setVisible(false);
        
        buttonAdd.setEnabled(true);
        buttonModify.setEnabled(true);
        buttonDelete.setEnabled(true);
        tableEvents.setEnabled(true);
    }//GEN-LAST:event_jButtonAddCancelActionPerformed

    private void jMenuItemOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemOpenActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            String url = "https://www.teluq.ca/site/infos/rss/communiques.php";
            this.notifyOpenRSS(url);
            
            DefaultTableModel model = (DefaultTableModel) tableEvents.getModel();
            this.notifyLoadTable(model);
            
            buttonAdd.setEnabled(true);
            buttonModify.setEnabled(true);
            buttonDelete.setEnabled(true);
            
        } catch (Exception ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItemOpenActionPerformed

    private void jMenuItemSaveAsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSaveAsActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        // Set current directory
        fileChooser.setCurrentDirectory(new File((System.getProperty("user.home"))));
        //open - SAVE dialog box
        int result = fileChooser.showSaveDialog(null);
        if(result == JFileChooser.APPROVE_OPTION){
            // get selected directory
            File selectedFile = fileChooser.getSelectedFile();
            String fileName = selectedFile.getAbsolutePath();

            try {
                this.notifySaveToXMLFile(fileName);
            } catch (Exception ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }

            JOptionPane.showMessageDialog(null,fileName);
        }
    }//GEN-LAST:event_jMenuItemSaveAsActionPerformed

    private void jMenuItemCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCloseActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jMenuItemCloseActionPerformed

    private void jCheckBoxGuidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxGuidActionPerformed
        // TODO add your handling code here:
        if(jTextFieldGuid.isEnabled()){
            jTextFieldGuid.setEnabled(false);
        } else {
            jTextFieldGuid.setEnabled(true);
        }       
    }//GEN-LAST:event_jCheckBoxGuidActionPerformed

    private void jCheckBoxDescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxDescriptionActionPerformed
        // TODO add your handling code here:
        if(jTextFieldDescription.isEnabled()){
            jTextFieldDescription.setEnabled(false);
        } else {
            jTextFieldDescription.setEnabled(true);
        }     
    }//GEN-LAST:event_jCheckBoxDescriptionActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void JMenuItemCollerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuItemCollerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JMenuItemCollerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem JMenuItemColler;
    private javax.swing.JButton buttonAdd;
    private javax.swing.JButton buttonDelete;
    private javax.swing.JButton buttonModify;
    private javax.swing.JCheckBox jCheckBoxDescription;
    private javax.swing.JCheckBox jCheckBoxGuid;
    private javax.swing.JFormattedTextField jFormattedTextFieldDate;
    private javax.swing.JLabel jLabelAddTitle;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanelAdd;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JTextField jTextFieldDescription;
    private javax.swing.JTextField jTextFieldGuid;
    private javax.swing.JTextField jTextFieldLink;
    private javax.swing.JTextField jTextFieldTitle;
    private javax.swing.JTable tableEvents;
    // End of variables declaration//GEN-END:variables
}
