package eventapp;

import java.awt.Font;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.xml.transform.TransformerException;

/**
 * @author Christopher Forget
 */

public class MainFrame extends javax.swing.JFrame {

    private Controller controller;

    public MainFrame(Controller controller) {
        initComponents();
        this.controller = controller;
        setLocationRelativeTo(null);
        tableEvents.getTableHeader().setFont(new Font("Arial", Font.PLAIN, 18));
        jPanelAdd.setVisible(false);
        jPanelModify.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanelDefault = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableEvents = new javax.swing.JTable();
        buttonAdd = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        buttonModify = new javax.swing.JButton();
        buttonDelete = new javax.swing.JButton();
        jPanelAdd = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldTitle = new javax.swing.JTextField();
        jFormattedTextFieldDate = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldLink = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldGuid = new javax.swing.JTextField();
        jButtonAddAccept = new javax.swing.JButton();
        jButtonAddCancel = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldDescription = new javax.swing.JTextField();
        jPanelModify = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldTitle1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jFormattedTextFieldDate1 = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldLink1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldGuid1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldDescription1 = new javax.swing.JTextField();
        jButtonModifyAccept = new javax.swing.JButton();
        jButtonModifyCancel = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuItemOpen = new javax.swing.JMenuItem();
        jMenuItemSave = new javax.swing.JMenuItem();
        jMenuItemSaveAs = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemClose = new javax.swing.JMenuItem();
        jMenuEdit = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EventApp");
        setPreferredSize(new java.awt.Dimension(1200, 900));
        setResizable(false);

        jLayeredPane1.setPreferredSize(new java.awt.Dimension(1200, 870));
        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelDefault.setPreferredSize(new java.awt.Dimension(1200, 870));

        jScrollPane1.setColumnHeaderView(null);
        jScrollPane1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jScrollPane1.setPreferredSize(new java.awt.Dimension(1160, 640));

        tableEvents.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tableEvents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title", "Link", "Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableEvents.setMaximumSize(new java.awt.Dimension(2147483647, 7000));
        tableEvents.setMinimumSize(new java.awt.Dimension(1160, 640));
        tableEvents.setPreferredSize(new java.awt.Dimension(1160, 670));
        tableEvents.setRowHeight(40);
        jScrollPane1.setViewportView(tableEvents);
        if (tableEvents.getColumnModel().getColumnCount() > 0) {
            tableEvents.getColumnModel().getColumn(0).setMinWidth(400);
            tableEvents.getColumnModel().getColumn(0).setPreferredWidth(400);
            tableEvents.getColumnModel().getColumn(1).setResizable(false);
            tableEvents.getColumnModel().getColumn(1).setPreferredWidth(400);
        }

        buttonAdd.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        buttonAdd.setText("Nouveau");
        buttonAdd.setFocusable(false);
        buttonAdd.setMaximumSize(new java.awt.Dimension(100, 30));
        buttonAdd.setMinimumSize(new java.awt.Dimension(100, 30));
        buttonAdd.setPreferredSize(new java.awt.Dimension(150, 60));
        buttonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eventapp/logoTeluq.png"))); // NOI18N
        jLabel1.setText("Fils de nouvelles RSS de l'université");

        buttonModify.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        buttonModify.setText("Modifier");
        buttonModify.setEnabled(false);
        buttonModify.setFocusable(false);
        buttonModify.setMaximumSize(new java.awt.Dimension(170, 70));
        buttonModify.setMinimumSize(new java.awt.Dimension(170, 70));
        buttonModify.setPreferredSize(new java.awt.Dimension(150, 60));
        buttonModify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonModifyActionPerformed(evt);
            }
        });

        buttonDelete.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        buttonDelete.setText("Supprimer");
        buttonDelete.setEnabled(false);
        buttonDelete.setFocusable(false);
        buttonDelete.setMaximumSize(new java.awt.Dimension(170, 70));
        buttonDelete.setMinimumSize(new java.awt.Dimension(170, 70));
        buttonDelete.setPreferredSize(new java.awt.Dimension(150, 60));
        buttonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelDefaultLayout = new javax.swing.GroupLayout(jPanelDefault);
        jPanelDefault.setLayout(jPanelDefaultLayout);
        jPanelDefaultLayout.setHorizontalGroup(
            jPanelDefaultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDefaultLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelDefaultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelDefaultLayout.createSequentialGroup()
                        .addComponent(buttonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonModify, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
        jPanelDefaultLayout.setVerticalGroup(
            jPanelDefaultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDefaultLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanelDefaultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonModify, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        jLayeredPane1.add(jPanelDefault, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 880));

        jPanelAdd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelAdd.setPreferredSize(new java.awt.Dimension(700, 543));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Ajouter un événement");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel2.setMaximumSize(new java.awt.Dimension(174, 46));
        jLabel2.setMinimumSize(new java.awt.Dimension(174, 46));
        jLabel2.setPreferredSize(new java.awt.Dimension(174, 46));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setText("Titre");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Date");

        jTextFieldTitle.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTextFieldTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTitleActionPerformed(evt);
            }
        });

        jFormattedTextFieldDate.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("Lien");

        jTextFieldLink.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextFieldLink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLinkActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Guid");

        jTextFieldGuid.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jButtonAddAccept.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButtonAddAccept.setText("Terminer");
        jButtonAddAccept.setFocusable(false);
        jButtonAddAccept.setPreferredSize(new java.awt.Dimension(150, 60));
        jButtonAddAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddAcceptActionPerformed(evt);
            }
        });

        jButtonAddCancel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButtonAddCancel.setText("Annuler");
        jButtonAddCancel.setPreferredSize(new java.awt.Dimension(150, 60));
        jButtonAddCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddCancelActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("Description");

        jTextFieldDescription.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanelAddLayout = new javax.swing.GroupLayout(jPanelAdd);
        jPanelAdd.setLayout(jPanelAddLayout);
        jPanelAddLayout.setHorizontalGroup(
            jPanelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAddLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldLink)
                    .addGroup(jPanelAddLayout.createSequentialGroup()
                        .addComponent(jButtonAddAccept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonAddCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextFieldTitle)
                    .addComponent(jTextFieldGuid)
                    .addComponent(jFormattedTextFieldDate)
                    .addComponent(jTextFieldDescription)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelAddLayout.createSequentialGroup()
                        .addGroup(jPanelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(20, 20, 20))
        );
        jPanelAddLayout.setVerticalGroup(
            jPanelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAddLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldLink, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldGuid, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jFormattedTextFieldDate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAddAccept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAddCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        jLayeredPane1.setLayer(jPanelAdd, javax.swing.JLayeredPane.MODAL_LAYER);
        jLayeredPane1.add(jPanelAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, -1, -1));

        jPanelModify.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelModify.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanelModify.setMaximumSize(new java.awt.Dimension(717, 32767));
        jPanelModify.setPreferredSize(new java.awt.Dimension(700, 543));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Modifier un événement");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel7.setMaximumSize(new java.awt.Dimension(174, 46));
        jLabel7.setMinimumSize(new java.awt.Dimension(174, 46));
        jLabel7.setPreferredSize(new java.awt.Dimension(174, 46));

        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setText("Titre");

        jTextFieldTitle1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextFieldTitle1.setMaximumSize(new java.awt.Dimension(663, 2147483647));
        jTextFieldTitle1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTitle1ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel10.setText("Date");

        jFormattedTextFieldDate1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jFormattedTextFieldDate1.setMaximumSize(new java.awt.Dimension(663, 2147483647));

        jLabel11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel11.setText("Lien");

        jTextFieldLink1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextFieldLink1.setMaximumSize(new java.awt.Dimension(663, 2147483647));
        jTextFieldLink1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLink1ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel12.setText("Guid");

        jTextFieldGuid1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextFieldGuid1.setMaximumSize(new java.awt.Dimension(663, 2147483647));

        jLabel13.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel13.setText("Description");

        jTextFieldDescription1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextFieldDescription1.setMaximumSize(new java.awt.Dimension(663, 2147483647));

        jButtonModifyAccept.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButtonModifyAccept.setText("Terminer");
        jButtonModifyAccept.setFocusable(false);
        jButtonModifyAccept.setPreferredSize(new java.awt.Dimension(150, 60));
        jButtonModifyAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModifyAcceptActionPerformed(evt);
            }
        });

        jButtonModifyCancel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButtonModifyCancel.setText("Annuler");
        jButtonModifyCancel.setPreferredSize(new java.awt.Dimension(150, 60));
        jButtonModifyCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModifyCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelModifyLayout = new javax.swing.GroupLayout(jPanelModify);
        jPanelModify.setLayout(jPanelModifyLayout);
        jPanelModifyLayout.setHorizontalGroup(
            jPanelModifyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelModifyLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelModifyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jFormattedTextFieldDate1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldLink1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldGuid1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldDescription1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldTitle1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelModifyLayout.createSequentialGroup()
                        .addGroup(jPanelModifyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(jLabel13))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelModifyLayout.createSequentialGroup()
                        .addComponent(jButtonModifyAccept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 358, Short.MAX_VALUE)
                        .addComponent(jButtonModifyCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );
        jPanelModifyLayout.setVerticalGroup(
            jPanelModifyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelModifyLayout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jFormattedTextFieldDate1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldLink1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldGuid1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldDescription1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanelModifyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonModifyAccept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonModifyCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        jLayeredPane1.setLayer(jPanelModify, javax.swing.JLayeredPane.POPUP_LAYER);
        jLayeredPane1.add(jPanelModify, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, -1, -1));

        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMenuBar1.setFocusable(false);
        jMenuBar1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jMenuBar1.setPreferredSize(new java.awt.Dimension(99, 30));

        jMenuFile.setText("Fichier");
        jMenuFile.setFocusable(false);
        jMenuFile.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jMenuItemOpen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemOpen.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jMenuItemOpen.setText("Ouvrir");
        jMenuItemOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemOpenActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemOpen);

        jMenuItemSave.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemSave.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jMenuItemSave.setText("Sauvegarder");
        jMenuFile.add(jMenuItemSave);

        jMenuItemSaveAs.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jMenuItemSaveAs.setText("Sauvegarder sous");
        jMenuItemSaveAs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSaveAsActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemSaveAs);
        jMenuFile.add(jSeparator1);

        jMenuItemClose.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jMenuItemClose.setText("Fermer");
        jMenuItemClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCloseActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemClose);

        jMenuBar1.add(jMenuFile);

        jMenuEdit.setText("Edit");
        jMenuEdit.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jMenuBar1.add(jMenuEdit);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 880, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1216, 908));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddActionPerformed
        // TODO add your handling code here:
        buttonAdd.setEnabled(false);
        buttonModify.setEnabled(false);
        buttonDelete.setEnabled(false);
        tableEvents.setEnabled(false);
        jPanelAdd.setVisible(true);
    }//GEN-LAST:event_buttonAddActionPerformed

    private void buttonModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonModifyActionPerformed
        // TODO add your handling code here:
        int selectedRow = tableEvents.getSelectedRow();
        
        if (selectedRow < 0){
            JOptionPane.showMessageDialog(this, "Aucune sélection, veuillez sélectionner une rangée.", "Erreur de sélection", JOptionPane.ERROR_MESSAGE);
        } else {
            buttonAdd.setEnabled(false);
            buttonModify.setEnabled(false);
            buttonDelete.setEnabled(false);
            tableEvents.setEnabled(false);
            jPanelModify.setVisible(true);  
                     
            int row = tableEvents.getSelectedRow();
            Event event = controller.getEvent(row);
            
            String title = event.getTitle();
            String link = event.getLink();
            String guid = event.getGuid();
            String pubDate = event.getPubDate();
            String desc = event.getDescription();
            
            jTextFieldTitle1.setText(title);
            jTextFieldLink1.setText(link);
            jTextFieldGuid1.setText(guid);
            jFormattedTextFieldDate1.setText(pubDate);
            jTextFieldDescription1.setText(desc);                     
        }
    }//GEN-LAST:event_buttonModifyActionPerformed

    private void buttonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteActionPerformed
        // TODO add your handling code here:
        int selectedRow = tableEvents.getSelectedRow();
        
        if (selectedRow < 0){
            JOptionPane.showMessageDialog(this, "Aucune sélection, veuillez sélectionner une rangée.", "Erreur de sélection", JOptionPane.ERROR_MESSAGE);
        } else {
            int row = tableEvents.getSelectedRow();
            controller.removeEvent(row);
            
            // Reload tableEvents
            DefaultTableModel model = (DefaultTableModel) tableEvents.getModel();
            controller.loadTreeToInterface(model);
        }
    }//GEN-LAST:event_buttonDeleteActionPerformed

    private void jTextFieldLinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLinkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLinkActionPerformed

    private void jTextFieldTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTitleActionPerformed

    private void jButtonAddAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddAcceptActionPerformed
        // TODO add your handling code here:
                
        // Get text fields entries
        String strTitle = jTextFieldTitle.getText();
        String strPubDate = jFormattedTextFieldDate.getText();
        String strLink = jTextFieldLink.getText();
        String strGuid = jTextFieldGuid.getText();
        String strDescription = jTextFieldDescription.getText();
        
        if (strTitle.isEmpty() || strPubDate.isEmpty() || strLink.isEmpty() || strGuid.isEmpty() || strDescription.isEmpty()){
            JOptionPane.showMessageDialog(this, "Formulaire incomplet, veuillez remplir toutes les cases", "Erreur de saisie", JOptionPane.ERROR_MESSAGE);
        } else {
            // Create an event and send to controller.
            Event newEvent = new Event(strTitle, strLink, strGuid, strPubDate, strDescription);
            controller.addEvent(newEvent);
        
            // Refresh tableEvents
            DefaultTableModel model = (DefaultTableModel) tableEvents.getModel();
            controller.loadTreeToInterface(model);
        
            // Reset and close form
            jTextFieldTitle.setText("");
            jFormattedTextFieldDate.setText("");
            jTextFieldLink.setText("");
            jTextFieldGuid.setText("");
            jTextFieldDescription.setText("");
            jPanelAdd.setVisible(false);     
            
            buttonAdd.setEnabled(true);
            buttonModify.setEnabled(true);
            buttonDelete.setEnabled(true);
            tableEvents.setEnabled(true);
        }
    }//GEN-LAST:event_jButtonAddAcceptActionPerformed

    private void jButtonAddCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddCancelActionPerformed
        // TODO add your handling code here:
        // Reset and close form
        jTextFieldTitle.setText("");
        jFormattedTextFieldDate.setText("");
        jTextFieldLink.setText("");
        jTextFieldGuid.setText("");
        jTextFieldDescription.setText("");
        jPanelAdd.setVisible(false);
        
        buttonAdd.setEnabled(true);
        buttonModify.setEnabled(true);
        buttonDelete.setEnabled(true);
        tableEvents.setEnabled(true);
    }//GEN-LAST:event_jButtonAddCancelActionPerformed

    private void jTextFieldTitle1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTitle1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTitle1ActionPerformed

    private void jTextFieldLink1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLink1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLink1ActionPerformed

    private void jButtonModifyAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModifyAcceptActionPerformed
        // TODO add your handling code here:
        String strTitle = jTextFieldTitle1.getText();
        String strPubDate = jFormattedTextFieldDate1.getText();
        String strLink = jTextFieldLink1.getText();
        String strGuid = jTextFieldGuid1.getText();
        String strDescription = jTextFieldDescription1.getText();
        
        if (strTitle.isEmpty() || strPubDate.isEmpty() || strLink.isEmpty() || strGuid.isEmpty() || strDescription.isEmpty()){
            JOptionPane.showMessageDialog(this, "Formulaire incomplet, veuillez remplir toutes les cases", "Erreur de saisie", JOptionPane.ERROR_MESSAGE);
        } else {
            // Create an event and send to controller.
            Event newEvent = new Event(strTitle, strLink, strGuid, strPubDate, strDescription);
            controller.modifyEvent(tableEvents.getSelectedRow(),newEvent);
        
            // Refresh tableEvents
            DefaultTableModel model = (DefaultTableModel) tableEvents.getModel();
            controller.loadTreeToInterface(model);
        
            // Reset and close form
            jTextFieldTitle1.setText("");
            jFormattedTextFieldDate1.setText("");
            jTextFieldLink1.setText("");
            jTextFieldGuid1.setText("");
            jTextFieldDescription1.setText("");
            jPanelModify.setVisible(false);     
            
            buttonAdd.setEnabled(true);
            buttonModify.setEnabled(true);
            buttonDelete.setEnabled(true);
            tableEvents.setEnabled(true);
        }
    }//GEN-LAST:event_jButtonModifyAcceptActionPerformed

    private void jButtonModifyCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModifyCancelActionPerformed
        // TODO add your handling code here:
        // Reset and close form
        jTextFieldTitle.setText("");
        jFormattedTextFieldDate.setText("");
        jTextFieldLink.setText("");
        jTextFieldGuid.setText("");
        jTextFieldDescription.setText("");
        jPanelModify.setVisible(false);
        
        buttonAdd.setEnabled(true);
        buttonModify.setEnabled(true);
        buttonDelete.setEnabled(true);
        tableEvents.setEnabled(true);
    }//GEN-LAST:event_jButtonModifyCancelActionPerformed

    private void jMenuItemOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemOpenActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            controller.openRSS("https://www.teluq.ca/site/infos/rss/communiques.php");
            
            DefaultTableModel model = (DefaultTableModel) tableEvents.getModel();
            controller.loadTreeToInterface(model);
            
            buttonModify.setEnabled(true);
            buttonDelete.setEnabled(true);
            
        } catch (Exception ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItemOpenActionPerformed

    private void jMenuItemSaveAsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSaveAsActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        // Set current directory
        fileChooser.setCurrentDirectory(new File((System.getProperty("user.home"))));
        //open - SAVE dialog box
        int result = fileChooser.showSaveDialog(null);
        if(result == JFileChooser.APPROVE_OPTION){
            // get selected directory
            File selectedFile = fileChooser.getSelectedFile();
            String fileName = selectedFile.getAbsolutePath();
            try {
                controller.saveToXMLFile(fileName);
            } catch (IOException | TransformerException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(null,fileName);
        }
    }//GEN-LAST:event_jMenuItemSaveAsActionPerformed

    private void jMenuItemCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCloseActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jMenuItemCloseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAdd;
    private javax.swing.JButton buttonDelete;
    private javax.swing.JButton buttonModify;
    private javax.swing.JButton jButtonAddAccept;
    private javax.swing.JButton jButtonAddCancel;
    private javax.swing.JButton jButtonModifyAccept;
    private javax.swing.JButton jButtonModifyCancel;
    private javax.swing.JFormattedTextField jFormattedTextFieldDate;
    private javax.swing.JFormattedTextField jFormattedTextFieldDate1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuEdit;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenuItem jMenuItemClose;
    private javax.swing.JMenuItem jMenuItemOpen;
    private javax.swing.JMenuItem jMenuItemSave;
    private javax.swing.JMenuItem jMenuItemSaveAs;
    private javax.swing.JPanel jPanelAdd;
    private javax.swing.JPanel jPanelDefault;
    private javax.swing.JPanel jPanelModify;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTextField jTextFieldDescription;
    private javax.swing.JTextField jTextFieldDescription1;
    private javax.swing.JTextField jTextFieldGuid;
    private javax.swing.JTextField jTextFieldGuid1;
    private javax.swing.JTextField jTextFieldLink;
    private javax.swing.JTextField jTextFieldLink1;
    private javax.swing.JTextField jTextFieldTitle;
    private javax.swing.JTextField jTextFieldTitle1;
    private javax.swing.JTable tableEvents;
    // End of variables declaration//GEN-END:variables
}
